server:
  port: 9909

spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/products
    username: postgres
    password: postgres
    jpa:
      show-sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL94Dialect

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost